package br.com.ecommerce.classe;
// Generated 18/11/2012 23:01:20 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Item generated by hbm2java
 */
@Entity
@Table(name="DESPESA", schema="public")  
public class Despesa  implements java.io.Serializable {

    
    private Integer cdDespesa;
    private BigDecimal vlDespesaTotal;
    private BigDecimal vlMargemLucro;
    

    public Despesa() {
    }

    @Id 
    @Column(name = "CD_DESPESA")
    public Integer getCdDespesa() {
		return cdDespesa;
	}

	public void setCdDespesa(Integer cdDespesa) {
		this.cdDespesa = cdDespesa;
	}
	
	@Column(name="VL_DESPESATOTAL", nullable=false, precision=14)
	public BigDecimal getVlDespesaTotal() {
		return vlDespesaTotal;
	}

	public void setVlDespesaTotal(BigDecimal vlDespesaTotal) {
		this.vlDespesaTotal = vlDespesaTotal;
	}

	@Column(name="VL_MARGEMLUCRO", nullable=false, precision=14)
	public BigDecimal getVlMargemLucro() {
		return vlMargemLucro;
	}

	public void setVlMargemLucro(BigDecimal vlMargemLucro) {
		this.vlMargemLucro = vlMargemLucro;
	}

	

    
    
}


