package br.com.ecommerce.classe;
// Generated 18/11/2012 23:01:20 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.math.BigInteger;
import java.math.RoundingMode;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import br.com.ecommerce.persistencia.DespesaDAO;
import br.com.ecommerce.persistencia.ItemDAO;

/**
 * Item generated by hbm2java
 */
@Entity
@Table(name="ITEM", schema="public")  
public class Item  implements java.io.Serializable {

    
    private Integer cdItem;
    private String dsItem;
    private String lgItem;
    private BigDecimal vlVenda;
    private BigDecimal vlVendaFinal;
    private Date dtRegistro;
    private String dsObservacao;
    

    public Item() {
    }

	
    public Item(Integer cdItem, String dsItem, String lgItem, BigDecimal vlVenda, Date dtRegistro, String dsObservacao) {
        this.cdItem = cdItem;
        this.dsItem = dsItem;
        this.lgItem = lgItem;
        this.vlVenda = vlVenda;
        this.dtRegistro = dtRegistro;
        this.dsObservacao = dsObservacao;
    }
    
    @Id 
    @Column(name = "CD_ITEM")
    public Integer getCdItem() {
        return this.cdItem;
    }
    
    public void setCdItem(Integer cdItem) {
        this.cdItem = cdItem;
    }
    
    @Column(name="DS_ITEM", nullable=false, length=60)
    public String getDsItem() {
        return this.dsItem;
    }
    
    public void setDsItem(String dsItem) {
        this.dsItem = dsItem;
    }
    
    @Column(name="LG_ITEM", length=60)
    public String getLgItem() {
		return lgItem;
	}


	public void setLgItem(String lgItem) {
		this.lgItem = lgItem;
	}

	@Column(name="VL_VENDA", nullable=false, precision=14)
    public BigDecimal getVlVenda() {
        return this.vlVenda;
    }
    
    public void setVlVenda(BigDecimal vlVenda) {
        this.vlVenda = vlVenda;
    }
    
    @Transient
    public BigDecimal getVlVendaFinal() {
    	DespesaDAO despesaDao = new DespesaDAO();
    	ItemDAO itemDao = new ItemDAO();
    	Despesa des = despesaDao.getDespesa(1);
    	
    	vlVendaFinal = this.vlVenda.add(des.getVlDespesaTotal().divide(new BigDecimal(itemDao.getItem().size()), 2, RoundingMode.HALF_UP));
    	vlVendaFinal = vlVendaFinal.add(vlVendaFinal.multiply(des.getVlMargemLucro()).divide(new BigDecimal(100)));
		return vlVendaFinal;
	}


	public void setVlVendaFinal(BigDecimal vlVendaFinal) {
		this.vlVendaFinal = vlVendaFinal;
	}


	@Temporal(TemporalType.TIMESTAMP)
    @Column(name="DT_RECORD", nullable=false, length=19)
    public Date getDtRegistro() {
        return this.dtRegistro;
    }
    
    public void setDtRegistro(Date dtRegistro) {
        this.dtRegistro = dtRegistro;
    }
    

	@Column(name="DS_OBSERVACAO", length=200)
	public String getDsObservacao() {
		return dsObservacao;
	}


	public void setDsObservacao(String dsObservacao) {
		this.dsObservacao = dsObservacao;
	}
	

    
    
}


