package br.com.ecommerce.classe;
// Generated 14/08/2012 20:24:10 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="USUARIO")
public class Usuario  implements java.io.Serializable {


     private Integer cdUsuario;
     private String dsUsuario;
     private String dsSenha;
     private char stUsuario;
     private Date dtRegistro;
     private String dsLogin;
     
    public Usuario() {
    }

    public Usuario(String dsSenha, char stUsuario, Date dtRegistro, String dsLogin) {
       this.dsSenha = dsSenha;
       this.stUsuario = stUsuario;
       this.dtRegistro = dtRegistro;
       this.dsLogin = dsLogin;
    }
   
    @Id 
    @Column(name="CD_USUARIO", unique=true, nullable=false)
    public Integer getCdUsuario() {
        return this.cdUsuario;
    }
    
    public void setCdUsuario(Integer cdUsuario) {
        this.cdUsuario = cdUsuario;
    }
    
    @Column(name="DS_USUARIO", nullable=false, length=100)
    public String getDsUsuario() {
        return dsUsuario;
    }

    public void setDsUsuario(String dsUsuario) {
        this.dsUsuario = dsUsuario;
    }
    
    @Column(name="DS_SENHA", nullable=false, length=20)
    public String getDsSenha() {
        return this.dsSenha;
    }
    
    public void setDsSenha(String dsSenha) {
        this.dsSenha = dsSenha;
    }
    
    @Column(name="ST_USUARIO", nullable=false, length=1)
    public char getStUsuario() {
        return this.stUsuario;
    }
    
    public void setStUsuario(char stUsuario) {
        this.stUsuario = stUsuario;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DT_RECORD", nullable=false, length=19)
    public Date getDtRegistro() {
        return this.dtRegistro;
    }
    
    public void setDtRegistro(Date dtRegistro) {
        this.dtRegistro = dtRegistro;
    }
    
    @Column(name="DS_LOGIN", nullable=false, length=45)
    public String getDsLogin() {
        return this.dsLogin;
    }
    
    public void setDsLogin(String dsLogin) {
        this.dsLogin = dsLogin;
    }


}


